### ISSUE TITLE
Being able to Register User

### ISSUE THREAD

**Issue by daanishgoyal** [daanishgoyal/myLearningPlace#3]
As a user, I would like to register myself at myLearningPlace.

**Comment by daanishgoyal** [comment]
Created User Information Table on Mysql

**Comment by daanishgoyal** [comment]
Successfully Established connection between Go and Mysql Server.

**Comment by akshayg1996** [comment]
Able to register a dummy user with mocked up backend

**Comment by daanishgoyal** [comment]
Successfully able to register user and store in database. Committed.
