### ISSUE TITLE
Being able to Login as a User

### ISSUE THREAD

**Issue by daanishgoyal** [daanishgoyal/myLearningPlace#4]
As a user, I would like to Login after I have registered myself.

**Comment by Aman2909** [comment]
Status: 
Created a route to facilitate login in.

**Comment by Aman2909** [comment]
Status:
Developed the core logic required to validate login a attempt

**Comment by akshayg1996** [comment]
Front-end: Able to login dummy user with mocked-up back-end

**Comment by daanishgoyal** [comment]
Added Login Functionality. Commited
